export default [
  {
    login: 'mikeour',
    id: 46303392,
    node_id: 'MDQ6VXNlcjQ2MzAzMzkz',
    avatar_url: 'https://avatars1.githubusercontent.com/u/46303393?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mikeour',
    html_url: 'https://github.com/mikeour',
    followers_url: 'https://api.github.com/users/mikeour/followers',
    following_url: 'https://api.github.com/users/mikeour/following{/other_user}',
    gists_url: 'https://api.github.com/users/mikeour/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mikeour/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mikeour/subscriptions',
    organizations_url: 'https://api.github.com/users/mikeour/orgs',
    repos_url: 'https://api.github.com/users/mikeour/repos',
    events_url: 'https://api.github.com/users/mikeour/events{/privacy}',
    received_events_url: 'https://api.github.com/users/mikeour/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'CodeWritingCow',
    id: 7751861,
    node_id: 'MDQ6VXNlcjc3NTE4NjI=',
    avatar_url: 'https://avatars2.githubusercontent.com/u/7751862?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/CodeWritingCow',
    html_url: 'https://github.com/CodeWritingCow',
    followers_url: 'https://api.github.com/users/CodeWritingCow/followers',
    following_url: 'https://api.github.com/users/CodeWritingCow/following{/other_user}',
    gists_url: 'https://api.github.com/users/CodeWritingCow/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/CodeWritingCow/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/CodeWritingCow/subscriptions',
    organizations_url: 'https://api.github.com/users/CodeWritingCow/orgs',
    repos_url: 'https://api.github.com/users/CodeWritingCow/repos',
    events_url: 'https://api.github.com/users/CodeWritingCow/events{/privacy}',
    received_events_url: 'https://api.github.com/users/CodeWritingCow/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'cali3192',
    id: 38990121,
    node_id: 'MDQ6VXNlcjM4OTkwMTI4',
    avatar_url: 'https://avatars2.githubusercontent.com/u/38990128?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/cali3192',
    html_url: 'https://github.com/cali3192',
    followers_url: 'https://api.github.com/users/cali3192/followers',
    following_url: 'https://api.github.com/users/cali3192/following{/other_user}',
    gists_url: 'https://api.github.com/users/cali3192/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/cali3192/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/cali3192/subscriptions',
    organizations_url: 'https://api.github.com/users/cali3192/orgs',
    repos_url: 'https://api.github.com/users/cali3192/repos',
    events_url: 'https://api.github.com/users/cali3192/events{/privacy}',
    received_events_url: 'https://api.github.com/users/cali3192/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'jakrim',
    id: 10550501,
    node_id: 'MDQ6VXNlcjEwNTUwNTAy',
    avatar_url: 'https://avatars3.githubusercontent.com/u/10550502?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jakrim',
    html_url: 'https://github.com/jakrim',
    followers_url: 'https://api.github.com/users/jakrim/followers',
    following_url: 'https://api.github.com/users/jakrim/following{/other_user}',
    gists_url: 'https://api.github.com/users/jakrim/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/jakrim/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jakrim/subscriptions',
    organizations_url: 'https://api.github.com/users/jakrim/orgs',
    repos_url: 'https://api.github.com/users/jakrim/repos',
    events_url: 'https://api.github.com/users/jakrim/events{/privacy}',
    received_events_url: 'https://api.github.com/users/jakrim/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'VladIgolnikov',
    id: 36962431,
    node_id: 'MDQ6VXNlcjM2OTYyNDM0',
    avatar_url: 'https://avatars3.githubusercontent.com/u/36962434?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/VladIgolnikov',
    html_url: 'https://github.com/VladIgolnikov',
    followers_url: 'https://api.github.com/users/VladIgolnikov/followers',
    following_url: 'https://api.github.com/users/VladIgolnikov/following{/other_user}',
    gists_url: 'https://api.github.com/users/VladIgolnikov/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/VladIgolnikov/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/VladIgolnikov/subscriptions',
    organizations_url: 'https://api.github.com/users/VladIgolnikov/orgs',
    repos_url: 'https://api.github.com/users/VladIgolnikov/repos',
    events_url: 'https://api.github.com/users/VladIgolnikov/events{/privacy}',
    received_events_url: 'https://api.github.com/users/VladIgolnikov/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'mikeour',
    id: 46303393,
    node_id: 'MDQ6VXNlcjQ2MzAzMzkz',
    avatar_url: 'https://avatars1.githubusercontent.com/u/46303393?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mikeour',
    html_url: 'https://github.com/mikeour',
    followers_url: 'https://api.github.com/users/mikeour/followers',
    following_url: 'https://api.github.com/users/mikeour/following{/other_user}',
    gists_url: 'https://api.github.com/users/mikeour/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mikeour/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mikeour/subscriptions',
    organizations_url: 'https://api.github.com/users/mikeour/orgs',
    repos_url: 'https://api.github.com/users/mikeour/repos',
    events_url: 'https://api.github.com/users/mikeour/events{/privacy}',
    received_events_url: 'https://api.github.com/users/mikeour/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'CodeWritingCow',
    id: 7751862,
    node_id: 'MDQ6VXNlcjc3NTE4NjI=',
    avatar_url: 'https://avatars2.githubusercontent.com/u/7751862?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/CodeWritingCow',
    html_url: 'https://github.com/CodeWritingCow',
    followers_url: 'https://api.github.com/users/CodeWritingCow/followers',
    following_url: 'https://api.github.com/users/CodeWritingCow/following{/other_user}',
    gists_url: 'https://api.github.com/users/CodeWritingCow/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/CodeWritingCow/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/CodeWritingCow/subscriptions',
    organizations_url: 'https://api.github.com/users/CodeWritingCow/orgs',
    repos_url: 'https://api.github.com/users/CodeWritingCow/repos',
    events_url: 'https://api.github.com/users/CodeWritingCow/events{/privacy}',
    received_events_url: 'https://api.github.com/users/CodeWritingCow/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'cali3192',
    id: 38990128,
    node_id: 'MDQ6VXNlcjM4OTkwMTI4',
    avatar_url: 'https://avatars2.githubusercontent.com/u/38990128?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/cali3192',
    html_url: 'https://github.com/cali3192',
    followers_url: 'https://api.github.com/users/cali3192/followers',
    following_url: 'https://api.github.com/users/cali3192/following{/other_user}',
    gists_url: 'https://api.github.com/users/cali3192/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/cali3192/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/cali3192/subscriptions',
    organizations_url: 'https://api.github.com/users/cali3192/orgs',
    repos_url: 'https://api.github.com/users/cali3192/repos',
    events_url: 'https://api.github.com/users/cali3192/events{/privacy}',
    received_events_url: 'https://api.github.com/users/cali3192/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'jakrim',
    id: 10550502,
    node_id: 'MDQ6VXNlcjEwNTUwNTAy',
    avatar_url: 'https://avatars3.githubusercontent.com/u/10550502?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/jakrim',
    html_url: 'https://github.com/jakrim',
    followers_url: 'https://api.github.com/users/jakrim/followers',
    following_url: 'https://api.github.com/users/jakrim/following{/other_user}',
    gists_url: 'https://api.github.com/users/jakrim/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/jakrim/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/jakrim/subscriptions',
    organizations_url: 'https://api.github.com/users/jakrim/orgs',
    repos_url: 'https://api.github.com/users/jakrim/repos',
    events_url: 'https://api.github.com/users/jakrim/events{/privacy}',
    received_events_url: 'https://api.github.com/users/jakrim/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'VladIgolnikov',
    id: 36962434,
    node_id: 'MDQ6VXNlcjM2OTYyNDM0',
    avatar_url: 'https://avatars3.githubusercontent.com/u/36962434?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/VladIgolnikov',
    html_url: 'https://github.com/VladIgolnikov',
    followers_url: 'https://api.github.com/users/VladIgolnikov/followers',
    following_url: 'https://api.github.com/users/VladIgolnikov/following{/other_user}',
    gists_url: 'https://api.github.com/users/VladIgolnikov/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/VladIgolnikov/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/VladIgolnikov/subscriptions',
    organizations_url: 'https://api.github.com/users/VladIgolnikov/orgs',
    repos_url: 'https://api.github.com/users/VladIgolnikov/repos',
    events_url: 'https://api.github.com/users/VladIgolnikov/events{/privacy}',
    received_events_url: 'https://api.github.com/users/VladIgolnikov/received_events',
    type: 'User',
    site_admin: false
  }
];
